Repository sixes-sense/back-end, pull requests merged in 2023-10, with the labels that each got.

#74 [Feat] : reviewtag 엔티티 추가
  .gitignore
  src/main/java/com/sixesSense/recorder/review/command/application/controller/CommandReviewController.java
  src/main/java/com/sixesSense/recorder/review/command/domain/aggregate/entity/ReviewTag.java
  src/main/java/com/sixesSense/recorder/review/command/domain/repository/ReviewLikesRepository.java
  src/test/java/com/sixesSense/recorder/review/command/application/service/CommandReviewTests.java
Labels: feature

#91 Refactor/tag : 태그 저장 restcontroller 구현 및 태그 관련 클래스명 변경
  src/main/java/com/sixesSense/recorder/tag/command/application/controller/CommandTagController.java
  src/main/java/com/sixesSense/recorder/tag/command/application/controller/CreateTagController.java
  src/main/java/com/sixesSense/recorder/tag/command/application/dto/CreateTagRequest.java
Labels: refactor

#89 Refactor/reportEntity : 신고 Entity 수정
  src/main/java/com/sixesSense/recorder/report/command/application/dto/response/CreateReportResponse.java
  src/main/java/com/sixesSense/recorder/report/command/domain/aggregate/entity/Report.java
Labels: refactor

#94 [Docs]: api swagger 작성
  src/main/java/com/sixesSense/recorder/achievements/query/application/controller/QueryAchievementsController.java
  src/main/java/com/sixesSense/recorder/achievements/query/application/dto/ReadAchievementsResponse.java
  src/main/java/com/sixesSense/recorder/achievements/query/domain/entity/Achievements.java
  src/main/resources/application-dev.yml
Labels: docs
