Repository sixes-sense/back-end, pull requests merged in 2023-08, with the labels that each got.

#11 Feature/report Entity 추가
  src/main/java/com/sixesSense/recorder/report/command/domain/aggregate/entity/Report.java
  src/main/java/com/sixesSense/recorder/report/command/domain/aggregate/vo/ReporterVo.java
  src/main/java/com/sixesSense/recorder/report/command/domain/aggregate/vo/ReviewVo.java
  src/main/java/com/sixesSense/recorder/report/command/domain/repository/ReportRepository.java
Labels: feature

#21 feat : 좋아요 기능 구현
  src/main/java/com/sixesSense/recorder/report/command/domain/aggregate/vo/ReporterVo.java
  src/main/java/com/sixesSense/recorder/review/command/application/controller/CommandReviewController.java
  src/main/java/com/sixesSense/recorder/review/command/application/dto/ReviewLikesDTO.java
  src/main/java/com/sixesSense/recorder/review/command/application/service/CommandReviewServiceImpl.java
  src/main/java/com/sixesSense/recorder/review/command/domain/aggregate/entity/Review.java
  src/main/java/com/sixesSense/recorder/review/command/domain/aggregate/entity/ReviewLikes.java
  src/main/java/com/sixesSense/recorder/review/command/domain/repository/ReviewLikesRepository.java
  src/main/java/com/sixesSense/recorder/review/command/domain/service/ReviewService.java
  src/main/java/com/sixesSense/recorder/review/command/infrastructure/service/ReviewValidService.java
  src/main/java/com/sixesSense/recorder/review/command/ininfrastructure/service/ReviewValidService.java
  src/main/java/com/sixesSense/recorder/review/query/domain/aggregate/entity/QueryReview.java
Labels: feature

#26 Bugfix/report_entity : Report Entity 수정 및 ReportType Enum 추가
  src/main/java/com/sixesSense/recorder/report/command/application/controller/ReportController.java
  src/main/java/com/sixesSense/recorder/report/command/application/dto/ReportDto.java
  src/main/java/com/sixesSense/recorder/report/command/application/service/ReportServiceImp.java
  src/main/java/com/sixesSense/recorder/report/command/domain/aggregate/entity/Report.java
  src/main/java/com/sixesSense/recorder/report/command/domain/aggregate/entity/enumtype/ReportType.java
  src/main/java/com/sixesSense/recorder/report/command/domain/aggregate/vo/ReporterVO.java
  src/main/java/com/sixesSense/recorder/report/command/domain/aggregate/vo/ReporterVo.java
  src/main/java/com/sixesSense/recorder/report/command/domain/aggregate/vo/ReviewInfoVO.java
  src/main/java/com/sixesSense/recorder/report/command/domain/service/ReportService.java
Labels: bugfix

#24 Feature/member : 패키지 생성 및 Member Entity 작성
  src/main/java/com/sixesSense/recorder/RecoderApplication.java
  src/main/java/com/sixesSense/recorder/common/entity/BaseTimeEntity.java
  src/main/java/com/sixesSense/recorder/member/command/application/controller/CommandMemberController.java
  src/main/java/com/sixesSense/recorder/member/command/application/dto/MemberDTO.java
  src/main/java/com/sixesSense/recorder/member/command/application/service/CommandMemberServiceImpl.java
  src/main/java/com/sixesSense/recorder/member/command/domain/aggregate/entity/Member.java
  src/main/java/com/sixesSense/recorder/member/command/domain/aggregate/entity/enumType/RoleEnum.java
  src/main/java/com/sixesSense/recorder/member/command/domain/repository/MemberRepository.java
  src/main/java/com/sixesSense/recorder/member/command/domain/service/CommandMemberService.java
  src/main/java/com/sixesSense/recorder/member/command/infrastructure/repository/Repository.java
  src/main/java/com/sixesSense/recorder/member/command/infrastructure/service/InfraCommandAchievementsService.java
  src/main/java/com/sixesSense/recorder/member/query/application/controller/QueryMemberController.java
  src/main/java/com/sixesSense/recorder/member/query/application/service/QueryMemberServiceImpl.java
  src/main/java/com/sixesSense/recorder/member/query/domain/aggregate/dto/MemberDTO.java
  src/main/java/com/sixesSense/recorder/member/query/domain/repository/MemberMapper.java
  src/main/java/com/sixesSense/recorder/member/query/domain/service/QueryAchievementsService.java
  src/main/java/com/sixesSense/recorder/member/query/infrastructure/service/InfraQueryMemberService.java
Labels: feature

#28 Feature/swagger 스웨거 적용
  build.gradle
  src/main/java/com/sixesSense/recorder/config/SwaggerConfiguration.java
Labels: feature

#29 Feature/review : 리뷰 리팩토링
  src/main/java/com/sixesSense/recorder/review/command/application/controller/CommandReviewController.java
  src/main/java/com/sixesSense/recorder/review/command/application/dto/ResponseMessage.java
  src/main/java/com/sixesSense/recorder/review/command/application/dto/ReviewDTO.java
  src/main/java/com/sixesSense/recorder/review/command/application/dto/ReviewLikesDTO.java
  src/main/java/com/sixesSense/recorder/review/command/application/dto/comment/request/CreateCommentRequest.java
  src/main/java/com/sixesSense/recorder/review/command/application/dto/comment/response/CreateCommentResponse.java
  src/main/java/com/sixesSense/recorder/review/command/application/dto/comment/response/UpdateCommentResponse.java
  src/main/java/com/sixesSense/recorder/review/command/application/dto/like/request/PostLikeRequest.java
  src/main/java/com/sixesSense/recorder/review/command/application/dto/like/response/PostLikeResponse.java
  src/main/java/com/sixesSense/recorder/review/command/application/dto/review/request/CreateReviewRequest.java
  src/main/java/com/sixesSense/recorder/review/command/application/dto/review/request/UpdateReviewRequest.java
  src/main/java/com/sixesSense/recorder/review/command/application/dto/review/response/CreateReviewResponse.java
  src/main/java/com/sixesSense/recorder/review/command/application/dto/review/response/UpdateReviewResponse.java
  src/main/java/com/sixesSense/recorder/review/command/application/service/CommandCommentServiceImpl.java
  src/main/java/com/sixesSense/recorder/review/command/application/service/CommandReviewServiceImpl.java
  src/main/java/com/sixesSense/recorder/review/command/domain/aggregate/entity/Comment.java
  src/main/java/com/sixesSense/recorder/review/command/domain/aggregate/entity/Review.java
  src/main/java/com/sixesSense/recorder/review/command/domain/aggregate/entity/ReviewLikes.java
  src/main/java/com/sixesSense/recorder/review/command/domain/aggregate/vo/ReviewTagVO.java
  src/main/java/com/sixesSense/recorder/review/command/domain/repository/CommentRepository.java
  src/main/java/com/sixesSense/recorder/review/command/domain/repository/ReviewRepository.java
  src/main/java/com/sixesSense/recorder/review/command/domain/service/CommentService.java
  src/main/java/com/sixesSense/recorder/review/command/domain/service/ReviewService.java
  src/main/java/com/sixesSense/recorder/review/command/infrastructure/service/ReviewValidService.java
  src/main/java/com/sixesSense/recorder/review/query/application/controller/QueryReviewController.java
  src/main/java/com/sixesSense/recorder/review/query/application/dto/QueryReviewDTO.java
  src/main/java/com/sixesSense/recorder/review/query/application/dto/response/ReadCommentResponse.java
  src/main/java/com/sixesSense/recorder/review/query/application/dto/response/ReadReviewResponse.java
  src/main/java/com/sixesSense/recorder/review/query/application/service/QueryCommentServiceImpl.java
  src/main/java/com/sixesSense/recorder/review/query/application/service/QueryReviewServiceImpl.java
  src/main/java/com/sixesSense/recorder/review/query/domain/aggregate/entity/QueryReview.java
  src/main/java/com/sixesSense/recorder/review/query/domain/repository/CommentMapper.java
  src/main/java/com/sixesSense/recorder/review/query/domain/repository/ReviewMapper.java
  src/main/java/com/sixesSense/recorder/review/query/domain/service/QueryCommentService.java
  src/main/java/com/sixesSense/recorder/review/query/domain/service/QueryReviewService.java
  src/main/java/com/sixesSense/recorder/review/query/infrastructure/service/QueryCommentValidService.java
  src/main/java/com/sixesSense/recorder/review/query/infrastructure/service/QueryReviewValidService.java
  src/main/resources/mappers/CommentMapper.xml
  src/main/resources/mappers/ReviewMapper.xml
  src/main/resources/sql/ddl.sql
  src/main/resources/sql/dml.sql
  src/test/java/com/sixesSense/recorder/review/command/application/controller/CommandCommentTests.java
  src/test/java/com/sixesSense/recorder/review/command/application/controller/CommandReviewTests.java
  src/test/java/com/sixesSense/recorder/review/command/application/controller/ReviewControllerTests.java
  src/test/java/com/sixesSense/recorder/review/command/application/controller/object/TestObjects.java
Labels: feature, bugfix, refactor

#32 Feature/board : 패키지 구조 생성
  src/main/java/com/sixesSense/recorder/board/command/application/controller/BoardController.java
  src/main/java/com/sixesSense/recorder/board/command/application/dto/BoardDTO.java
  src/main/java/com/sixesSense/recorder/board/command/application/service/BoardService.java
  src/main/java/com/sixesSense/recorder/board/command/domain/aggregate/entity/Board.java
  src/main/java/com/sixesSense/recorder/board/command/domain/repository/BoardRepository.java
  src/main/java/com/sixesSense/recorder/board/command/domain/service/BoardService.java
  src/main/java/com/sixesSense/recorder/board/command/infrastructure/repository/BoardInfraRepo.java
  src/main/java/com/sixesSense/recorder/board/command/infrastructure/service/BoardInfraService.java
  src/main/java/com/sixesSense/recorder/board/query/application/controller/QueryBoardController.java
  src/main/java/com/sixesSense/recorder/board/query/application/dto/QueryBoardDTO.java
  src/main/java/com/sixesSense/recorder/board/query/application/service/QueryBoardService.java
  src/main/java/com/sixesSense/recorder/board/query/domain/entity/QueryBoard.java
  src/main/java/com/sixesSense/recorder/board/query/domain/service/QueryBoardService.java
  src/main/java/com/sixesSense/recorder/board/query/infrastructure/repository/BoardMapper.java
  src/main/java/com/sixesSense/recorder/board/query/infrastructure/service/BoardInfraService.java
Labels: feature

#36 Feature/tag : 태그 저장 기능
  src/main/java/com/sixesSense/recorder/tag/command/application/controller/CreateTagController.java
  src/main/java/com/sixesSense/recorder/tag/command/application/dto/CreateTagDTO.java
  src/main/java/com/sixesSense/recorder/tag/command/application/service/CreateTagServiceImpl.java
  src/main/java/com/sixesSense/recorder/tag/command/domain/aggregate/entity/Tag.java
  src/main/java/com/sixesSense/recorder/tag/command/domain/repository/TagRepository.java
  src/main/java/com/sixesSense/recorder/tag/command/domain/service/TagService.java
  src/test/java/com/sixesSense/recorder/tag/command/application/service/CreateTagServiceImplTest.java
Labels: feature, test

#51 Refactor/tag : 태그 저장 기능 수정
  src/main/java/com/sixesSense/recorder/tag/command/application/dto/CreateTagRequest.java
  src/main/java/com/sixesSense/recorder/tag/command/application/service/CreateTagServiceImpl.java
  src/main/java/com/sixesSense/recorder/tag/command/domain/repository/TagRepository.java
  src/main/java/com/sixesSense/recorder/tag/command/domain/service/TagService.java
  src/test/java/com/sixesSense/recorder/tag/command/application/service/CreateTagServiceImplTest.java
  src/test/java/com/sixesSense/recorder/tag/command/application/service/CreateTagServiceImplTests.java
Labels: refactor, test

#38 Test/report : 신고 서비스 테스트 코드 작성
  src/main/java/com/sixesSense/recorder/report/command/application/dto/ReportDto.java
  src/main/java/com/sixesSense/recorder/report/command/application/dto/request/CreateReportRequest.java
  src/main/java/com/sixesSense/recorder/report/command/application/dto/response/CreateReportResponse.java
  src/main/java/com/sixesSense/recorder/report/command/application/service/CommandReportServiceImp.java
  src/main/java/com/sixesSense/recorder/report/command/application/service/ReportServiceImp.java
  src/main/java/com/sixesSense/recorder/report/command/domain/aggregate/entity/Report.java
  src/main/java/com/sixesSense/recorder/report/command/domain/aggregate/vo/ReviewInfoVO.java
  src/main/java/com/sixesSense/recorder/report/command/domain/service/ReportService.java
  src/test/java/com/sixesSense/recorder/report/command/application/controller/object/TestObjects.java
  src/test/java/com/sixesSense/recorder/report/command/application/service/ReportServiceTest.java
Labels: feature, test

#55 Feature/tag : 태그 삭제 기능 구현, 조회 기능 추가
  src/main/java/com/sixesSense/recorder/tag/command/application/service/CommandTagServiceImpl.java
  src/main/java/com/sixesSense/recorder/tag/command/domain/service/TagService.java
  src/main/java/com/sixesSense/recorder/tag/query/application/service/QueryTagServiceImpl.java
  src/main/java/com/sixesSense/recorder/tag/query/domain/entity/QueryTag.java
  src/main/java/com/sixesSense/recorder/tag/query/domain/repository/QueryTagRepository.java
  src/main/java/com/sixesSense/recorder/tag/query/domain/service/QueryTagService.java
  src/test/java/com/sixesSense/recorder/tag/command/application/service/CommandTagServiceImplTests.java
  src/test/java/com/sixesSense/recorder/tag/query/application/service/QueryTagServiceImplTest.java
Labels: feature, test

#64 Feature/common [공통] 환경설정 관리
  .github/workflows/prtest.yml
  build.gradle
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: feature

#65 Feature/report_cnt : 신고 수 증가 및 숨김 처리
  src/main/java/com/sixesSense/recorder/report/command/application/service/CommandReportServiceImp.java
  src/main/java/com/sixesSense/recorder/review/command/domain/aggregate/entity/Review.java
Labels: feature
